import Head from 'next/head'
import { Inter, Poppins } from '@next/font/google'
import Image from 'next/image';
import profilePic from '../public/me.png';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Pascal Nabare</title>
        <meta name="description" content="Generated by create next app" />
        pic.png   <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gradient-to-l from-gray-600 to-zinc-900 '>
        <section className= 'bg-zinc-500 sticky top-1'>
          <nav className='py-5 flex justify-between text-white' >
            <ul className='flex items-center'>
            <li><a href='#' className='px-4 '>Home</a></li>
            <li><a href='#' className='px-4 bg-black py-2 mx-2 rounded-lg'>About Me</a></li>
            <li><a href='#' className='px-4 bg-black py-2 mx-2 rounded-lg'>Contact</a></li>
            </ul>
            <ul className='flex items-center'>
              <li><a href='#' className='px-4'>Resume</a></li>
              <li><a href='#' className='px-4'>LinkedIn</a></li>
              <li><a href='#' className='px-4'>Github</a></li>
            </ul>
          </nav>
        </section>
        <section id="sec" className=''>
          <div id='hey' className='text-slate-200 text-center p-20'>
            Hey! I'm <br/> Pascal Nabare 
          </div>
          <div id="mypic" className=''>
            <Image src={profilePic} 
            alt="picture of pascal" 
             />
          </div>
          <div id="welcome" className='text-2xl text-slate-300 text-center'>
            <h1>
              WELCOME TO MY WEBSITE
            </h1>
            <p>
              I'm a sophomore at Princeton University majoring in <br/>Computer Science

            </p>
          </div>
        </section>

      </main>
  
    </>
  ); 
}
